; -------------------------------------------------------------------------------------------------------------------
; GAME OF LIFE
; -------------------------------------------------------------------------------------------------------------------
;
; [BOARD]
; Width  - board width in cells (min = 10, max = 120)
; Height - board height in cells (min = 10, max = 50)
;
; If invalid values are specified, default values (average) are used.
;
; [DISPLAY]
; DeadCell - text used to display a dead cell (default " ")
; LiveCell - text used to display a live cell (default "#")
;
; DeadCell and LiveCell glyphs must be different. They may contain spaces or be empty (only DeadCell).
; The maximum cell width is 2 characters. Longer values are truncated.
; If their lengths are different, the shorter value is padded with spaces on the right.
; If invalid characters are specified, default values are used.
;
; [INITIAL_STATE]
; Defines the initial state of the cells.
; The Width and Height values from the BOARD section must be preserved. If the number of rows (height)
; or the rows size (width) differs from the BOARD section dimensions, the layout is automatically
; truncated or extended to match the dimensions specified in the BOARD section.
; A single character in the grid represents a cell:
;    '.' - set the cell as dead
;    '#' - set the cell as alive
; Any other character is treated as an error and prevents the game from starting.
;
; NOTE: Multiple sections containing initial configurations can be prepared.
; Each additional section must have a unique suffix added to its name.
; The active initial state is selected by renaming its section to INITIAL_STATE.
;
; -------------------------------------------------------------------------------------------------------------------

[BOARD]
Width=80
Height=40

[DISPLAY]
DeadCell=
LiveCell=#

[INITIAL_STATE]
#...............................................................................
#.###........................................................#..................
..#..........................................................#..................
...#....###.........#..........#...........................###..................
##......#.....................##................................................
.........#..........##.........#............................##..................
....................#.......................................#........#..........
.....................#.....................................###......#...........
..............................................................#.....###.........
............................................................#...................
...........................................................##...................
.....................................#......................#...................
...#...............................#.#..........................................
...#.....................##......##............##.............#.................
...###..................#...#....##............##............#..................
.............##........#.....#...##..........................###................
.............##........#...#.##....#.#..........................................
.......................#.....#.......#..........................................
........................#...#...................................................
.........................##.....................................................
................................................................................
................................................................................
..............................................................#.................
.............................................................#..................
.............................................................#..................
...........................................................#.##.................
............................................................#.#.................
.............................................................#.......#..........
...............#...........................................##.......##..........
...............##..........................................#.........#..........
...............#..........................................#.....................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................


[INITIAL_STATE_1]
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
......................................#.........................................
........................................#.......................................
.....................................##..###....................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................
................................................................................


